package com.facilcomanda.authservice.service;
import com.facilcomanda.authservice.entity.*; import com.facilcomanda.authservice.repository.*; import com.facilcomanda.common.dto.*; import com.facilcomanda.common.event.EventPublisher; import com.facilcomanda.common.security.JwtService;
import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service;
@Service
public class AuthService {
 private final AuthUserRepository users; private final AuthRoleRepository roles; private final AuthOrganizationRepository orgs; private final JwtService jwt; private final PasswordEncoder encoder; private final EventPublisher publisher;
 public AuthService(AuthUserRepository users, AuthRoleRepository roles, AuthOrganizationRepository orgs, JwtService jwt, PasswordEncoder encoder, EventPublisher publisher){this.users=users;this.roles=roles;this.orgs=orgs;this.jwt=jwt;this.encoder=encoder;this.publisher=publisher;}
 public UserAuthDTO register(RegisterRequest request){ if(users.findByEmail(request.email()).isPresent()) throw new RuntimeException("User with this email already exists."); orgs.findById(request.organizationId()).orElseThrow(() -> new RuntimeException("Organization not found.")); AuthRole role=roles.findById(request.roleId()).orElseThrow(() -> new RuntimeException("Role not found.")); AuthUser user=new AuthUser(); user.setEmail(request.email()); user.setFirstName(request.firstName()); user.setLastName(request.lastName()); user.setOrganizationId(request.organizationId()); user.setRole(role); user.setPassword(encoder.encode(request.password())); AuthUser saved=users.save(user); UserAuthDTO dto=new UserAuthDTO(saved.getId(), saved.getEmail(), saved.getFirstName(), saved.getLastName(), role.getName(), saved.getOrganizationId()); publisher.publishAudit("auth-service","User",saved.getId(),"CREATE",null,dto,null,null,null,null); return dto; }
 public LoginResponse login(LoginRequest request){ AuthUser user=users.findByEmail(request.email()).orElseThrow(() -> new RuntimeException("Usuario no encontrado")); if(!encoder.matches(request.password(), user.getPassword())) throw new RuntimeException("Credenciales invalidas"); String token=jwt.generateToken(user.getEmail(), user.getOrganizationId(), user.getRole().getName().name()); return new LoginResponse(token, new UserAuthDTO(user.getId(), user.getEmail(), user.getFirstName(), user.getLastName(), user.getRole().getName(), user.getOrganizationId())); }
}
