package com.facilcomanda.productservice.service;
import com.facilcomanda.common.dto.*; import com.facilcomanda.common.event.EventPublisher; import com.facilcomanda.productservice.client.CategoryClient; import com.facilcomanda.productservice.entity.Product; import com.facilcomanda.productservice.repository.ProductRepository; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class ProductService { private final ProductRepository repo; private final CategoryClient categories; private final EventPublisher publisher; public ProductService(ProductRepository repo, CategoryClient categories, EventPublisher publisher){this.repo=repo;this.categories=categories;this.publisher=publisher;}
 public ProductResponse createProduct(ProductRequest request, Long org){Product p=new Product(); p.setOrganizationId(org); map(request,p,org); Product saved=repo.save(p); ProductResponse res=toResponse(saved,org); audit("CREATE",saved.getId(),null,res); return res;}
 public List<ProductResponse> getAllProducts(Long org){return repo.findByOrganizationId(org).stream().map(p -> toResponse(p,org)).toList();}
 public ProductResponse getProductById(Long id,Long org){return toResponse(fetch(id,org),org);}
 public ProductSnapshot getProductSnapshot(Long id,Long org){Product p=fetch(id,org); return new ProductSnapshot(p.getId(),p.getName(),p.getUnitPrice(),p.getDiscount(),p.getStock());}
 public ProductResponse updateProduct(Long id,ProductRequest r,Long org){Product p=fetch(id,org); ProductResponse old=toResponse(p,org); map(r,p,org); ProductResponse res=toResponse(repo.save(p),org); audit("UPDATE",id,old,res); return res;}
 public void deleteProduct(Long id,Long org){Product p=fetch(id,org); ProductResponse old=toResponse(p,org); repo.delete(p); audit("DELETE",id,old,null);}
 @Transactional public ProductSnapshot reserveStock(Long id, Integer quantity, Long org){Product p=fetch(id,org); if(p.getStock()<quantity) throw new RuntimeException("Insufficient stock for product: "+p.getName()); p.setStock(p.getStock()-quantity); repo.save(p); publisher.publishAudit("product-service","Product",id,"UPDATE_STOCK",null,getProductSnapshot(id,org),null,null,null,null); return getProductSnapshot(id,org);}
 private Product fetch(Long id,Long org){return repo.findByIdAndOrganizationId(id,org).orElseThrow(() -> new RuntimeException("Product not found or access denied"));}
 private void map(ProductRequest r,Product p,Long org){p.setName(r.name()); p.setDescription(r.description()); p.setStock(r.stock()); p.setUnitPrice(r.unitPrice()); p.setDiscount(r.discount()); p.setExpirationDate(r.expirationDate()); Set<Long> ids=new HashSet<>(); if(r.categoryIds()!=null) for(Long id:r.categoryIds()){categories.getCategory(id,org); ids.add(id);} p.setCategoryIds(ids);}
 private ProductResponse toResponse(Product p,Long org){List<Long> ids=p.getCategoryIds()==null?List.of():new ArrayList<>(p.getCategoryIds()); List<String> names=ids.stream().map(id -> categories.getCategory(id,org).name()).toList(); return new ProductResponse(p.getId(),p.getName(),p.getDescription(),p.getStock(),p.getUnitPrice(),p.getDiscount(),p.getExpirationDate(),ids,names);}
 private void audit(String op,Object id,Object old,Object val){publisher.publishAudit("product-service","Product",id,op,old,val,null,null,null,null);}
}
