spring:
  application:
    name: discovery-server
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
server:
  port: ${PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
