package com.facilcomanda.restaurantservice.service;
import com.facilcomanda.common.dto.*; import com.facilcomanda.common.event.EventPublisher; import com.facilcomanda.restaurantservice.entity.*; import com.facilcomanda.restaurantservice.repository.*; import org.springframework.stereotype.Service; import java.util.List;
@Service public class RestaurantService { private final OrganizationRepository orgs; private final RestaurantFloorRepository floors; private final EventPublisher publisher; public RestaurantService(OrganizationRepository orgs, RestaurantFloorRepository floors, EventPublisher publisher){this.orgs=orgs;this.floors=floors;this.publisher=publisher;}
 public OrganizationResponse createOrganization(OrganizationRequest r){Organization o=new Organization(); o.setName(r.name()); o.setTaxIdentificationNumber(r.taxIdentificationNumber()); o.setTaxIdentificationType(r.taxIdentificationType()); Organization saved=orgs.save(o); OrganizationResponse res=toOrg(saved); audit("Organization","CREATE",saved.getId(),null,res); return res;}
 public OrganizationResponse getOrganizationById(Long id){return toOrg(orgs.findById(id).orElseThrow(() -> new RuntimeException("Organization not found")));}
 public OrganizationResponse updateOrganization(Long id, OrganizationRequest r){Organization o=orgs.findById(id).orElseThrow(() -> new RuntimeException("Organization not found")); OrganizationResponse old=toOrg(o); o.setName(r.name()); o.setTaxIdentificationNumber(r.taxIdentificationNumber()); o.setTaxIdentificationType(r.taxIdentificationType()); OrganizationResponse res=toOrg(orgs.save(o)); audit("Organization","UPDATE",id,old,res); return res;}
 private OrganizationResponse toOrg(Organization o){return new OrganizationResponse(o.getId(),o.getName(),o.getTaxIdentificationNumber(),o.getTaxIdentificationType());}
 public RestaurantFloorResponse createFloor(RestaurantFloorRequest r, Long org){RestaurantFloor f=new RestaurantFloor(); f.setOrganizationId(org); f.setName(r.name()); f.setDescription(r.description()); RestaurantFloor saved=floors.save(f); RestaurantFloorResponse res=toFloor(saved); audit("RestaurantFloor","CREATE",saved.getId(),null,res); return res;}
 public List<RestaurantFloorResponse> getAllFloors(Long org){return floors.findByOrganizationId(org).stream().map(this::toFloor).toList();}
 public RestaurantFloorResponse getFloorById(Long id, Long org){return toFloor(fetchFloor(id,org));}
 public RestaurantFloorResponse updateFloor(Long id, RestaurantFloorRequest r, Long org){RestaurantFloor f=fetchFloor(id,org); RestaurantFloorResponse old=toFloor(f); f.setName(r.name()); f.setDescription(r.description()); RestaurantFloorResponse res=toFloor(floors.save(f)); audit("RestaurantFloor","UPDATE",id,old,res); return res;}
 public void deleteFloor(Long id, Long org){RestaurantFloor f=fetchFloor(id,org); RestaurantFloorResponse old=toFloor(f); floors.delete(f); audit("RestaurantFloor","DELETE",id,old,null);}
 private RestaurantFloor fetchFloor(Long id,Long org){return floors.findByIdAndOrganizationId(id,org).orElseThrow(() -> new RuntimeException("Floor not found or unauthorized"));}
 private RestaurantFloorResponse toFloor(RestaurantFloor f){return new RestaurantFloorResponse(f.getId(), f.getName(), f.getDescription(), f.getOrganizationId());}
 private void audit(String entity,String op,Object id,Object old,Object val){publisher.publishAudit("restaurant-service",entity,id,op,old,val,null,null,null,null);}
}
